name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérification du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Étape 3: Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4: Lancement des tests unitaires
      - name: Run tests
        run: |
          pytest

      # Étape 5: Déploiement sur EC2
      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}
        run: |
          sshpass -p "$EC2_PASSWORD" ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'

            # Change to the application directory
            cd /home/ec2-user/fastapi_template

            # Pull the latest code
            git pull origin main

            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart the application service
            sudo systemctl restart gunicorn
          EOF
